### PR TITLE
Added dashes to pig latin

### PR DESCRIPTION
**Pull request by SirDagen**
Since this challenge is in principle unsolveable, I suggest to add hyphens in the translation as a guide to reversibility. Otherwise back translation is sometimes just guessing, or having to match every word against a full dictionary of the English language: 

oolschay -> school
oolschay -> chools

### CODE REVIEW

**Review by Nova-Ardent — COMMENTED** [review]
No. Also check for spelling. The challenge was heavily dumbed down for a reason.

**Comment by Nova-Ardent** [comment]
in addition, adding dashes increases the potential of having the same problem the original question had.

**Comment by Pyroseza** [comment]
https://cdn.discordapp.com/attachments/483979558249562112/567793735329382401/unknown.png

Double check the one commit there, you say `ass` instead of `add`

**Comment by Nova-Ardent** [comment]
I'm still rejecting this change. This question is labelled easy, and was WAY to hard for its state. This change just brings it back to its original state, of being too hard for its rating if not impossible due to bi-direction transformation of the phrases.

**Review by Nova-Ardent — COMMENTED** [review]
Can't do that, people have already completed it and have been rewarded points.

**Comment by SirDagen** [comment]
So? I too got points for it. I don't mind.

**Comment by Nova-Ardent** [comment]
> 
> 
> So? I too got points for it. I don't mind. That's live. It's risky to be an early adopter.

Not everything needs to reference the uncertainty and unfairness of real life.

**Comment by SirDagen** [comment]
I really don't understand the importance of the challenge points. It's a fun thing, it keeps people push forward in the solving of the challenges, it solves its purpose. But may you think of it as you may...

Regarding the pig latin challenge: I don't see the point of removing it. It is great fun, it is challenging and it helps people to learn coding. I gave my best to improve it so far as to meet all requirements given to me. It is logical, it is now bi-directionally transformational, but it still doesnt get love?

**Comment by Nova-Ardent** [comment]
There is a leaderboard.

**Pull request merged**
