### PR TITLE
Added a new challenge for EMKC challenges.

### PR DESCRIPTION
**Pull request by Akanate**
This challenge works by the player being given a string of short or long length they then have to find the most common character or characters if they are the same amount and then output it.

### CODE REVIEW

**Comment by realtux** [comment]
there seems to be lots of blank lines in the html and json. could you remove all these please?

**Comment by Akanate** [comment]
> there seems to be lots of blank lines in the html and json. could you remove all these please?

By that do you mean the lines at the bottom like whitespace.

**Comment by realtux** [comment]
lines 2, 4, 6, 7, 8, etc.

**Comment by Akanate** [comment]
> lines 2, 4, 6, 7, 8, etc.

I think ive fixed it but does it update automatically for you.

**Pull request merged**
